### ISSUE TITLE
make cubical release

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/Stimela#615]
@JSKenyon @SpheMakh can you please pin cubical to a release or otherwise a specific refspec. As it stands each time there is a new commit on cubical a new image will be build making it impossible to keep track of what is going on. I prefer rolling back to a previous release version of cubical until this is fixed

**Comment by SpheMakh** [comment]
I thought I had pinned it to a specific commit. 

```
RUN git clone -b decasacore300fication https://github.com/ratt-ru/CubiCal
```

Is that not how you do it?

**Comment by SpheMakh** [comment]
The problem we were trying to fix with that commit did not really exist anyway. So it's better to depend on the latest

**Comment by JSKenyon** [comment]
That will pin to a branch, not a specific commit. So every time that branch gets updated, it will be "new". If there is something missing from the latest release, please open a PR for it because, as Ben points out, depending on an evolving branch (which I had no idea existed as it turns out) is likely to be fraught with problems.

**Comment by JSKenyon** [comment]
Ah ok @SpheMakh, all good.

**Comment by bennahugo** [comment]
No you have to check out a refspec. I changed it back to the release
version which works fine for my de calibration.
